# Generated by Django 4.0.4 on 2022-06-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=45)),
                ('book_des', models.CharField(max_length=10)),
                ('book_img', models.ImageField(upload_to='thumbnails')),
                ('book_author', models.CharField(max_length=50)),
                ('book_publisher', models.CharField(max_length=50)),
                ('book_gener', models.CharField(max_length=20)),
                ('book_year', models.CharField(max_length=5)),
                ('book_cost', models.CharField(max_length=50)),
            ],
        ),
    ]
