# Generated by Django 4.0.4 on 2022-06-26 13:45

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='book_name', unique=True),
        ),
    ]
